### ISSUE TITLE
线性代数辅导讲义编译问题

### ISSUE THREAD

**Issue by SynTime** [yhwu-is/Linear-Algebra-I-H-for-ZJU-CKC#101]
线性代数荣誉课辅学讲义中有多处"??"的编译结果错误。如P45公式2.2下面一行；P46证明；P56等处

**Comment by 45gfg9** [comment]
GitHub Actions 的 CI 构建是正常的，详见 <https://github.com/yhwu-is/Linear-Algebra-Left-Undone/actions>. 在未提供更多信息的情况下，我们无法帮助您的编译问题.
