### ISSUE TITLE
复数乘法的引入是否依赖于分配律？

### ISSUE THREAD

**Issue by zgyxclyty** [yhwu-is/Linear-Algebra-I-H-for-ZJU-CKC#106]
在pdf文件32页（书本页码9）定理1.3引入复数域的乘法的时候，是否应当将分配律作为条件给出？否则在证明的第一步，$`\mathbf{u} \circ \mathbf{v}=(a\mathbf{e_1}+b\mathbf{e_2})\circ(c\mathbf{e_1}+d\mathbf{e_2})=ac\mathbf{e_1}+(ad+bc)\mathbf{e_2}+bd\mathbf{e_1}\circ\mathbf{e_2}`$是如何得到的？
比如这个反例：定义$`(a,b) \circ (c,d)=\begin{cases}
(ac,ad) & b=0 \\
(ac,bc) & d=0 \\
(ac+bd,ad-bc) & b和d均不为0
\end{cases}`$
应该是符合单位元和长度可乘的吧？
还是说乘法这一声明隐含了分配律？or我构造的反例有问题？

**Comment by FrightenedFoxCN** [comment]
是.

这里我们在引入复数乘法的时候，假定的它是“复数域中的乘法”，而域中的乘法对域中的加法分配，这是定义域的时候所要求的.

---

补充：这个地方表述貌似亦须修改，可参见 Dorman et al. 的论文和 W. W. Willson 的论文，麻烦 @yhwu-is 在后续的修改中补充一下.

**Comment by zgyxclyty** [comment]
谢谢。另外，能顺便问一个同样在第一章的问题吗？就是关于在B组习题中的零环问题：在给定条件下，结合律与左右分配律是平凡的。但是我无法确认乘法单位元的存在（A为环<=>乘法单位元存在<=>A中只有0一个元素）。

**Comment by FrightenedFoxCN** [comment]
> 谢谢。另外，能顺便问一个同样在第一章的问题吗？就是关于在B组习题中的零环问题：在给定条件下，结合律与左右分配律是平凡的。但是我无法确认乘法单位元的存在（A为环<=>乘法单位元存在<=>A中只有0一个元素）。

这个习题的前提是乘法单位元必须存在，我们随后会修改其措辞。

如果乘法单位元不存在，那么实际上任取一个 Abel 群都可以满足这个条件，只需强行定义这样的乘法即可。

这是一些历史性的因素造成的，在早些时候，人们定义环并不要求乘法单位元，这也是前面给出的定义。但是，现代的资料往往要求乘法单位元的存在性，出题人应该误解了这点。在一些现代的资料中，会将不要求乘法单位元的环称作 Rng，题给的条件是 Rng of square zero，要求的证明则是表明 Rng of square zero 的 Ring（有乘法单位元的环）只有一个,就是零环。

**Comment by zgyxclyty** [comment]
谢谢。
