### ISSUE TITLE
v0.6 改动后出现的新问题

### ISSUE THREAD

**Issue by VictorWang712** [yhwu-is/Linear-Algebra-I-H-for-ZJU-CKC#111]
相较于 v0.5 的例 3.6：
![image](https://github.com/user-attachments/assets/8455d7e4-8d13-4b4d-9dff-7c96b264fb2a)

v0.6 删去了这一例题：
![image](https://github.com/user-attachments/assets/3da7d7ed-8342-4f17-a572-375fa4bab951)

从而导致了 v0.6 的例 3.13 出现了引用问题：
![image](https://github.com/user-attachments/assets/74fe3aab-55ea-4007-bf8f-ac6c5df3e7b0)

这就导致了现在的 v0.6 中，始终缺少一道求极大线性无关组的完整例题解答。个人认为这个还是比较重要的，建议把例 v0.5 中的例 3.6 补充回来。

**Comment by yhwu-is** [comment]
删去这一例子的原因是，0.6的例3.10相当于已经给出了求解极大线性无关组的方法
当然考虑到后面引用的问题，下次提交会将例3.13转换为例3.10的数据重新引用
谢谢提醒
