### ISSUE TITLE
关于“构造性证明”的讨论

### ISSUE THREAD

**Issue by kaixuanwang2003** [yhwu-is/Linear-Algebra-I-H-for-ZJU-CKC#41]
预备思想章节中用这个命题作为非构造性证明的例子：
$$
              证明：存在无理数 $x, y$ 使得 $x^y$ 为有理数.
              假定 $\sqrt{2}^{\sqrt{2}}$ 为有理数，则原命题得证；假定其为无理数，则 $\left(\sqrt{2}^{\sqrt{2}}\right)^{\sqrt{2}}$ 为有理数，原命题仍得证.
$$
我感觉这个不能算是严格的非构造性证明了，因为还是构造出了一个具体的数，只是没有对这个数是否是有理数做出定论。严格意义上非构造性证明应该是不依赖于具体的什么例子的。

**Comment by FrightenedFoxCN** [comment]
这里我们的写法确实有欠妥当，因为有一个隐含的问题是，构造性证明（作为日常语言）和构造主义证明（作为一个严格的学派的思想）之间是稍有不同的，而这个证明是明确的“非构造主义证明”而不一定是日常含糊说的“非构造性证明”。在此，因为读者很多是计算机专业的学生，而构造主义对计算机科学影响颇多，不妨对构造主义证明稍加解释，以供有兴趣的读者参考。

首先我们要问的是，怎么诠释一个证明？构造主义（或者说，直觉主义）的观点被称为 BHK 诠释（布劳威尔-海廷-哥尔戈莫洛夫诠释）。他们的想法核心是，如果有一个命题 $p$ 的证明，则它应该“见证”（witness） $p$ 的成立，也就是说：

- $p \wedge q$ 的证明是 $(r, s)$，其中 $r$ 是 $p$ 的证明， $s$ 是 $q$ 的证明；
- $p \vee q$ 的证明是一个 $(n, s)$，其中 $n$ 是 $0$ 或 $1$，标识证明的是哪个分支， $s$ 是对应分支的证明；
- $p \to q$ 的证明是一个算法 $A$，它将 $p$ 的证明作为输入， $q$ 的证明作为输出；
- $\lnot p$ 的证明是 $p \to \bot$ 的证明， $\bot$ 表示矛盾；
- $\forall x. p(x)$ 的证明是一个算法 $A$，它将 $x$ 作为输入， $p(x)$ 的证明作为输出；
- $\exists x. p(x)$ 的证明是 $(x_0, s)$，$x_0$ 为论域中的元素， $s$ 为 $p(x_0)$ 的证明；

当然，这是最原始的版本，有些版本还会写出“算法正确性证明”。注意其中关于“或”和“存在”的证明，这也是为什么这里我们认为它是非构造主义的证明，因为它说，要么左边是对的，要么右边是对的，但没有给出到底左边是对的还是右边是对的，这是违背了 BHK 诠释的要求的。

这里有一个显然的问题：在 BHK 诠释下，排中律不成立。这也是我们在这一节中强调排中律的原因。因此，构造主义证明可以被粗略看作“除去排中律”的证明，而上述命题的证明也显然地应用了排中律。反证和否证的“文字游戏”也来源于此。

至于这套诠释体系有什么用，一方面它提供了一个研究可计算性的思路，即可实现性（realizability）的思想，Kleene 可实现性无非是将证明严格化成按照自然数编码的证明，同时，它对很多证明助手（autoprover）来说也是非常有用的；另一方面，它把握了我们日常所谓“构造性”和“非构造性”证明的直觉的一个方面，因此能够更形式化地解释这种证明思想。这里的观点不一致就是因为我们不希望在正文中（但是应该会在 Discrete Mathematics Made Concrete 系列的正文中）探讨这些证明论的形而上争议，而试图按照直觉的方式解释它的问题。

一个直觉的“构造性证明”的案例（Euler 常数存在的例子）在新版本文件中应已经加上，作为补充的案例。关于构造主义的入门级参考可见于 [SEP 中对应的条目](https://plato.stanford.edu/entries/mathematics-constructive/)。
