### ISSUE TITLE
13讲 行列式 小语病

### ISSUE THREAD

**Issue by Williamdepig** [yhwu-is/Linear-Algebra-I-H-for-ZJU-CKC#48]
https://github.com/yhwu-is/Linear-Algebra-Left-Undone/blob/7fae188dff9b2e855c0adc5f2493c18e7ef7af6f/%E8%AE%B2%E4%B9%89/%E4%B8%93%E9%A2%98/13%20%E8%A1%8C%E5%88%97%E5%BC%8F.tex#L30
应从**公理化定义从是逆序数定义可以推导出的**改为**公理化定义是可以从逆序数定义推导出的**。

**Comment by yhwu-is** [comment]
感谢提醒，下次更新进行修改
