### ISSUE TITLE
关于下载的问题

### ISSUE THREAD

**Issue by forward-rowan** [yhwu-is/Linear-Algebra-I-H-for-ZJU-CKC#57]
![github](https://github.com/yhwu-is/Linear-Algebra-Left-Undone/assets/120050888/343c2882-0056-4ec8-803e-c6366e0da487)
我在下载讲义，进行到这一步的时候出现这种问题，请问如何解决，拜托大佬，我是个高中生，虚心请教！！

**Comment by 45gfg9** [comment]
Hi，欢迎来到 LALU 的仓库～

其实如果你只是希望下载并获得一份目前最新的讲义的话，只需要前往 Actions 选项卡，进入最新一次 workflow 下载 artifact 就行，如图：
<img width="1324" alt="截屏2024-03-03 16 51 13" src="https://github.com/yhwu-is/Linear-Algebra-Left-Undone/assets/37043529/a90c0d2e-bf20-4a1d-9d23-03fe71852095">

`git clone` 适合想要参与 LALU 的写作的朋友们，你的这种情况我推测是 mingw git bash 的编码问题，但不确定（因为我手头没有 Windows 环境来测试）。实际上在 `Linear-Algebra-Left-Undone` 目录下可以直接通过 `make main` 和 `make ans` 来分别构建讲义与参考答案，不需要通过手动 `make -C <目录名>`。

**Comment by forward-rowan** [comment]
感谢楼上的朋友，问题解决啦，啊哈哈哈，我还是个git小白，为了这个项目学习了4小时git，因为想知道到底怎么下载成功，总之非常感谢！！！！！然后我通过您的提示试了一下，出现了这个情况
![github-1](https://github.com/yhwu-is/Linear-Algebra-Left-Undone/assets/120050888/20b77777-cd18-42a7-beaf-52a9d345ec6b)
