### ISSUE TITLE
107页例5.8小bug

### ISSUE THREAD

**Issue by FishDraw-ch** [yhwu-is/Linear-Algebra-I-H-for-ZJU-CKC#63]
v0.4版107页例5.8中的“连续函数”应改为“光滑函数”，毕竟该例中的线性空间V要求对求导运算封闭

**Comment by FishDraw-ch** [comment]
110页证明(3)中“存在\beta\in v”应为“存在\beta\in V”

**Comment by FishDraw-ch** [comment]
111页证明的第三行中，“因此只需证明 dim(ker σ + im σ) ⩾ n/2”应该为“因此只需证明 dim(ker σ + im σ) \leqslant n/2”；第七行中，“故若 dim(ker σ + im σ) > n/2”应改为“故若 dim(ker σ \cap im σ) >n/2”

**Comment by yhwu-is** [comment]
感谢指出问题，下次提交进行更正
