### ISSUE TITLE
参考文献一处链接不太对劲

### ISSUE THREAD

**Issue by smd1121** [yhwu-is/Linear-Algebra-I-H-for-ZJU-CKC#64]
是蓄意为之吗🥺

https://github.com/yhwu-is/Linear-Algebra-Left-Undone/blob/2428614766e548e2efaa31ca0875fb1cba447e39/%E8%AE%B2%E4%B9%89/%E5%85%B6%E5%AE%83/%E5%BA%8F.tex#L42

**Comment by 45gfg9** [comment]
绷，大概是全局替换 . 为。的时候所为 ~~，下次一起修复~~ 哦，原来发 pr 了

**Comment by smd1121** [comment]
乐 原来如此！
