### ISSUE TITLE
english translation

### ISSUE THREAD

**Issue by bytearchive** [yhwu-is/Linear-Algebra-I-H-for-ZJU-CKC#71]
can you please add english translations

**Comment by 45gfg9** [comment]
Hello,

We're sorry but this lecture is primarily written for students of Zhejiang University, and we currently don't have a plan for multilingual support. Meanwhile our book is (largely) inspired by [Linear Algebra Done Right](https://linear.axler.net) written by Sheldon Axler, you can check that out instead.
