### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by yo666666yo** [yhwu-is/Linear-Algebra-I-H-for-ZJU-CKC#75]
请问docker被墙了以后还怎么手动编译呀😭😭😭

**Comment by 45gfg9** [comment]
您可以选择在本机上安装 TeX Live 进行编译，或自行寻找可用的 Docker Hub 镜像.

**Comment by yo666666yo** [comment]
好的！谢谢

**Comment by yo666666yo** [comment]
同学您好，我尝试了下载texlive但是下载了一半就失败，我也不太清楚为什么，然后换成miktex后，就不清楚怎么用make来编译了，我用终端输入make以后总是会有各种各样奇怪的报错，求解答😭😭😭



在 2024-09-08 17:25:57，"45gfg9" ***@***.***> 写道：

您可以选择在本机上安装 TeX Live 进行编译，或自行寻找可用的 Docker Hub 镜像.

**Comment by yo666666yo** [comment]
用gitbash就是这个问题，我尝试了两天了还是不会搞




在 2024-09-09 15:58:53，"yoyo_Lee" ***@***.***> 写道：

同学您好，我尝试了下载texlive但是下载了一半就失败，我也不太清楚为什么，然后换成miktex后，就不清楚怎么用make来编译了，我用终端输入make以后总是会有各种各样奇怪的报错，求解答



在 2024-09-08 17:25:57，"45gfg9" ***@***.***> 写道：

您可以选择在本机上安装 TeX Live 进行编译，或自行寻找可用的 Docker Hub 镜像.
