### ISSUE TITLE
在 git bash 下使用 make 指令报错 无法正常生成 PDF 文档

### ISSUE THREAD

**Issue by VictorWang712** [yhwu-is/Linear-Algebra-I-H-for-ZJU-CKC#93]
情况如图
![image](https://github.com/user-attachments/assets/d42941ef-e406-4d0f-843b-87dff49488c3)

附一张 make 工具的版本信息：
![image](https://github.com/user-attachments/assets/785fdaad-6de8-4850-9ae8-6fc771197bb3)

**Comment by 45gfg9** [comment]
Duplicate of #57 

已知 mingw32-make 无法正确处理 UTF-8 编码，请使用非 mingw32-make 的其他版本 make 进行编译。

**Comment by VictorWang712** [comment]
能给一个参考方案吗？

**Comment by 45gfg9** [comment]
若不需要参与 LALU 的编写，可直接前往 Releases 下载正式版本，或在 Actions 选项卡中下载 CI 构建版本。

**Comment by VictorWang712** [comment]
谢谢
