### ISSUE TITLE
v0.5 answer P18 的两处笔误

### ISSUE THREAD

**Issue by VictorWang712** [yhwu-is/Linear-Algebra-I-H-for-ZJU-CKC#96]
![image](https://github.com/user-attachments/assets/28afb6b1-f299-4639-83c2-9909a51ef177)

如图所示，第一处的 $u$ 应改为 $U$，第二处的 $n - 2$ 应改为 $n - 1$.

**Comment by VictorWang712** [comment]
再补充同一页另一处：

![image](https://github.com/user-attachments/assets/da2db077-736b-4972-bb1e-e364fdbf27fe)

该处 $W_{1} \cap W_{2}$ 应改为 $W_{1} \cap W_{0}$.

同时建议该句补充逗号以避免错误理解，即改为“由于 $W_{1} \cap W_{0}, W_{2} \cap W_{0},\cdots , W_{s} \cap W_{0}$ 都是 $W_{0}$ 的子空间”

**Comment by FrightenedFoxCN** [comment]
第一处，这一小题的答案表述问题很大，所有 $u$ 都应改为 $U$，“由于 $u$ 为对称矩阵”应改为“由于 $U$ 中的矩阵均为对称矩阵”，估计是这一部分的作者取了 $u \in U$ 但没有叙述清楚之类的
